// https://nuxt.com/docs/api/configuration/nuxt-config
import { parse as parseYaml } from 'yaml'

export default defineNuxtConfig({
  modules: [
    '@nuxt/eslint',
    '@nuxt/image',
    '@nuxt/ui',
    '@vueuse/nuxt',
    'nuxt-og-image',
    'motion-v/nuxt',
    '@nuxtjs/i18n'
  ],

  devtools: {
    enabled: process.env.NODE_ENV === 'development'
  },

  css: ['~/assets/css/main.css'],

  compatibilityDate: '2026-05-26',

  nitro: {
    preset: 'cloudflare_module',
    sourceMap: false,
    minify: false,
    cloudflare: {
      deployConfig: false,
      nodeCompat: true
    },
    // No prerendering: Nuxt pages render on request in the Worker. The English homepage (public/index.html)
    // and the blog (public/blog, generated by blog/build.mjs) are static assets served before the Worker runs.
    prerender: {
      crawlLinks: false,
      routes: []
    }
  },

  vite: {
    plugins: [{
      // lets app/utils/content.ts import the YAML in content/ as plain objects
      name: 'yaml',
      transform(code, id) {
        if (id.endsWith('.yml') || id.endsWith('.yaml')) return { code: `export default ${JSON.stringify(parseYaml(code))}`, map: null }
      }
    }],
    build: {
      sourcemap: false,
      chunkSizeWarningLimit: 1000
    }
  },

  eslint: {
    config: {
      stylistic: {
        commaDangle: 'never',
        braceStyle: '1tbs'
      }
    }
  },

  i18n: {
    locales: [
      {
        code: 'en',
        iso: 'en-US',
        name: 'English',
        file: 'en.json'
      },
      {
        code: 'ja',
        iso: 'ja-JP',
        name: '日本語',
        file: 'ja.json'
      },
      {
        code: 'de',
        iso: 'de-DE',
        name: 'Deutsch',
        file: 'de.json'
      }
    ],
    defaultLocale: 'en',
    strategy: 'prefix_except_default',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root'
    }
  },

  ogImage: {
    zeroRuntime: true
  }
})
