// Every bit of page chrome that changes with the language.
// Posts live in blog/posts/<lang>/. English is served at /blog, the others at /<lang>/blog.

export const LANGS = {
  en: {
    name: 'English',
    home: '/',
    blogTitle: 'Notes',
    label: 'things I wrote down',
    sub: 'On building products, <em>flaky Bluetooth</em>, and keeping big systems boring.',
    metaDescription: 'Notes by Zafar on building products, realtime systems, Bluetooth and AI tooling.',
    latest: 'latest',
    read: 'read it',
    minRead: n => `${n} min read`,
    min: n => `${n} min`,
    back: 'all notes',
    newer: 'newer',
    older: 'older',
    alsoIn: 'also in',
    resume: 'résumé',
    blog: 'blog',
    sayHi: 'say hi',
    lamp: 'Switch the lights',
    turn: 'your turn',
    next: 'What are we building next?',
    cta: 'Grab 30 minutes',
    footer: 'made by hand in Tokyo · no frameworks'
  },
  ja: {
    name: '日本語',
    home: '/ja',
    blogTitle: 'Notes',
    label: '書き留めたこと',
    sub: 'プロダクトづくり、<em>切れやすいBluetooth</em>、大きなシステムを退屈に保つことについて。',
    metaDescription: 'Zafarによる、プロダクト開発、リアルタイムシステム、Bluetooth、AIツールについてのメモ。',
    latest: '最新',
    read: '読む',
    minRead: n => `${n}分で読めます`,
    min: n => `${n}分`,
    back: 'すべてのノート',
    newer: '新しい',
    older: '古い',
    alsoIn: '他の言語',
    resume: '履歴書',
    blog: 'ブログ',
    sayHi: '連絡する',
    lamp: 'ライトを切り替える',
    turn: 'あなたの番',
    next: '次は何をつくりましょう？',
    cta: '30分話しましょう',
    footer: '東京で手づくり · フレームワークなし'
  },
  de: {
    name: 'Deutsch',
    home: '/de',
    blogTitle: 'Notizen',
    label: 'Dinge, die ich aufgeschrieben habe',
    sub: 'Über Produkte, <em>wackeliges Bluetooth</em> und darüber, große Systeme langweilig zu halten.',
    metaDescription: 'Notizen von Zafar über Produktentwicklung, Echtzeitsysteme, Bluetooth und KI-Werkzeuge.',
    latest: 'neu',
    read: 'lesen',
    minRead: n => `${n} Min. Lesezeit`,
    min: n => `${n} Min.`,
    back: 'alle Notizen',
    newer: 'neuer',
    older: 'älter',
    alsoIn: 'auch auf',
    resume: 'Lebenslauf',
    blog: 'Blog',
    sayHi: 'Hallo sagen',
    lamp: 'Licht umschalten',
    turn: 'du bist dran',
    next: 'Was bauen wir als Nächstes?',
    cta: '30 Minuten buchen',
    footer: 'von Hand gemacht in Tokio · ohne Frameworks'
  }
}

export const DEFAULT_LANG = 'en'
